In [3]:
# 1. Imports & Settings
import pandas as pd
import numpy as np
import glob
import os

# display all columns
pd.set_option('display.max_columns', None)

In [4]:
# 1. File path & discovery
data_path = 'data/'
pattern = os.path.join(data_path, '*_Climate*.csv')

file_list = glob.glob(pattern)
print(f'Found {len(file_list)} files:')
for f in file_list:
    print(' •', os.path.basename(f))

# 2. Read files with proper encoding and new 'date_format' parameter
df_list = []
for f in file_list:
    try:
        df = pd.read_csv(
            f,
            encoding='ISO-8859-1',
            parse_dates=['Date'],
            date_format='%d-%m-%Y'  # ✅ preferred method now
        )
        df_list.append(df)
    except Exception as e:
        print(f'❌ Error reading {f}: {e}')

# 3. Combine all data
df_all = pd.concat(df_list, ignore_index=True)
print(f'\n✅ Combined DataFrame shape: {df_all.shape}')

Found 10 files:
 • 202401_Climate.csv
 • 202402_Climate.csv
 • 202403_Climate.csv
 • 202405_Climate.csv
 • 202406_Climate.csv
 • 202407_Climate.csv
 • 202410_Climate.csv
 • 202411_Climate.csv
 • 202412_Climate.csv
 • 202501_Climate.csv

✅ Combined DataFrame shape: (306, 21)

In [5]:
# 3. Quick peek
df_all.head()

,Date,Minimum temperature (°C),Maximum temperature (°C),Rainfall (mm),Evaporation (mm),Sunshine (hours),Direction of maximum wind gust,Speed of maximum wind gust (km/h),Time of maximum wind gust,9am Temperature (°C),9am relative humidity (%),9am cloud amount (oktas),9am wind direction,9am wind speed (km/h),9am MSL pressure (hPa),3pm Temperature (°C),3pm relative humidity (%),3pm cloud amount (oktas),3pm wind direction,3pm wind speed (km/h),3pm MSL pressure (hPa)
0,01/01/24,12.6,23.2,0.0,7.2,11.4,SSW,31.0,14:35,17.6,65,7,SW,4,1021.7,22.5,60,7.0,SSW,13,1017.7
1,02/01/24,16.9,24.7,0.0,6.8,3.3,SW,41.0,14:23,19.6,81,7,NNW,7,1017.4,21.9,77,8.0,SW,15,1014.8
2,03/01/24,17.8,26.9,17.8,5.8,3.6,S,30.0,21:34,19.3,100,7,,Calm,1015.4,26.3,70,7.0,S,6,1013.3
3,04/01/24,17.8,21.9,1.0,4.0,3.2,SSW,33.0,17:46,18.3,80,8,SSW,11,1020.1,20.3,71,7.0,SSW,15,1019.8
4,05/01/24,15.9,28.9,0.0,4.8,5.7,SE,31.0,18:48,19.9,81,7,NW,6,1021.2,26.4,58,6.0,SSW,9,1019.0

In [6]:
# 4. Structure & dtypes
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306 entries, 0 to 305
Data columns (total 21 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Date                               306 non-null    object
 1   Minimum temperature (°C)           304 non-null    float64
 2   Maximum temperature (°C)           304 non-null    float64
 3   Rainfall (mm)                      304 non-null    float64
 4   Evaporation (mm)                   306 non-null    float64
 5   Sunshine (hours)                   306 non-null    float64
 6   Direction of maximum wind gust     301 non-null    object
 7   Speed of maximum wind gust (km/h)  301 non-null    float64
 8   Time of maximum wind gust          301 non-null    object
 9   9am Temperature (°C)               306 non-null    float64
 10  9am relative humidity (%)          306 non-null    int64
 11  9am cloud amount (oktas)           306 non-null    int64
 12  9am wind direction                 306 non-null    object
 13  9am wind speed (km/h)              306 non-null    object
 14  9am MSL pressure (hPa)             306 non-null    float64
 15  3pm Temperature (°C)               306 non-null    float64
 16  3pm relative humidity (%)          306 non-null    int64
 17  3pm cloud amount (oktas)           305 non-null    float64
 18  3pm wind direction                 306 non-null    object
 19  3pm wind speed (km/h)              306 non-null    object
 20  3pm MSL pressure (hPa)             306 non-null    float64
dtypes: float64(11), int64(3), object(7)
memory usage: 50.3+ KB

In [7]:
# 5. Missing‑value summary
missing = df_all.isnull().sum().sort_values(ascending=False)
print(missing[missing > 0])

Direction of maximum wind gust       5
Speed of maximum wind gust (km/h)    5
Time of maximum wind gust            5
Maximum temperature (°C)             2
Rainfall (mm)                        2
Minimum temperature (°C)             2
3pm cloud amount (oktas)             1
dtype: int64

In [8]:
# 6. Descriptive statistics (numeric)
df_all.describe().T

,count,mean,std,min,25%,50%,75%,max
Minimum temperature (°C),304.0,12.674342,4.645655,1.0,9.300,12.95,16.225,22.8
Maximum temperature (°C),304.0,21.958553,6.696164,10.1,16.875,21.25,25.725,39.8
Rainfall (mm),304.0,1.492763,4.832885,0.0,0.000,0.00,0.200,37.8
Evaporation (mm),306.0,5.481373,3.679159,0.0,2.200,5.60,7.600,18.0
Sunshine (hours),306.0,7.160784,3.913847,0.0,4.100,7.95,10.575,13.6
Speed of maximum wind gust (km/h),301.0,34.112957,10.745256,13.0,28.000,33.00,41.000,69.0
9am Temperature (°C),306.0,15.844118,5.289958,2.3,12.100,16.40,19.100,30.7
9am relative humidity (%),306.0,70.816993,16.008579,28.0,59.000,69.00,82.000,100.0
9am cloud amount (oktas),306.0,5.071895,2.619234,0.0,3.000,7.00,7.000,8.0
9am MSL pressure (hPa),306.0,1018.538562,7.801821,997.5,1013.350,1018.15,1023.275,1041.5
3pm Temperature (°C),306.0,20.527451,6.325475,9.1,16.100,19.95,23.800,37.8
3pm relative humidity (%),306.0,55.215686,17.273856,12.0,45.000,55.00,65.000,100.0
3pm cloud amount (oktas),305.0,4.501639,2.624686,0.0,2.000,5.00,7.000,8.0
3pm MSL pressure (hPa),306.0,1016.763072,7.773269,997.4,1011.725,1016.20,1021.700,1039.9

In [9]:
# 7. Identify categorical vs numeric
numeric_cols     = df_all.select_dtypes(include=['number']).columns.tolist()
categorical_cols = df_all.select_dtypes(include=['object']).columns.tolist()

print('Numeric columns   :', numeric_cols)
print('Categorical cols  :', categorical_cols)

Numeric columns   : ['Minimum temperature (°C)', 'Maximum temperature (°C)', 'Rainfall (mm)', 'Evaporation (mm)', 'Sunshine (hours)', 'Speed of maximum wind gust (km/h)', '9am Temperature (°C)', '9am relative humidity (%)', '9am cloud amount (oktas)', '9am MSL pressure (hPa)', '3pm Temperature (°C)', '3pm relative humidity (%)', '3pm cloud amount (oktas)', '3pm MSL pressure (hPa)']
Categorical cols  : ['Date', 'Direction of maximum wind gust ', 'Time of maximum wind gust', '9am wind direction', '9am wind speed (km/h)', '3pm wind direction', '3pm wind speed (km/h)']

In [10]:
# 9. Handling missing values

# — Drop rows where > 50% of columns are missing
thresh = df_all.shape[1] * 0.5
df_clean = df_all.dropna(thresh=thresh)

# — Fill remaining numeric with median
for col in numeric_cols:
    med = df_clean[col].median()
    df_clean[col] = df_clean[col].fillna(med)

# — Fill categorical with mode
for col in categorical_cols:
    if df_clean[col].isnull().any():
        mode = df_clean[col].mode()[0]
        df_clean[col] = df_clean[col].fillna(mode)

# confirm
print('\nPost‑clean missing counts:')
print(df_clean.isnull().sum()[df_clean.isnull().sum() > 0])

Post‑clean missing counts:
Series([], dtype: int64)

In [11]:
# 10. Save cleaned dataset
out_path = 'data/climate_all_cleaned.csv'
df_clean.to_csv(out_path, index=False)
print(f'✅ Cleaned data written to {out_path}')

✅ Cleaned data written to data/climate_all_cleaned.csv